### ISSUE TITLE
Create Bespoke tool demo

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk#119]
The SMK has a tool that acts as a hook for custom development, the Bespoke tool. We should create a minimal sample in the SMK repo that demonstrates the pattern for creating a custom Vue component for the Bespoke tool and put the sample alongside the other samples in the debug directory of the SMK repo.

**Comment by michaelpnelson** [comment]
This was implemented in pull request https://github.com/bcgov/smk/pull/165.
