### ISSUE TITLE
WMS and WFS should be completely different input types.. 

### ISSUE THREAD

**Issue by webgismich** [bcgov/smk#38]
When you click on a WMS to (point or polygon) identify, why do WFS GetFeature? .. and not WMS Getfeatureinfo? I can understand WFS if it is for a ‘selected set' but this should be explicitly different than using a WMS service..

 (not all WMS have equivalent WFS, and this will eliminate basic query access of a WMS service (that doesn't offer WFS at the same URL). WFS and WMS should be completely different input types in SMK.

**Comment by NicoledeGreef** [comment]
smk-cli beta3+ supports this
