### ISSUE TITLE
A panel that the application is responsible for populating

### ISSUE THREAD

**Issue by qqnluaq** [bcgov/smk#44]
A tool that shows a panel that the application is responsible for populating.
The app gets notified when the panel is initialized, activated, and deactivated.

> This is a feature added for WFONE app, and the implementation is contained in
> https://github.com/qqnluaq/smk-client/tree/feature/wfone

**Comment by michaelpnelson** [comment]
Hi @qqnluaq . We're reviewing older SMK issues and I'm checking in on this one. Is the functionality requested here already implemented in the Bespoke tool? Thanks ...

**Comment by qqnluaq** [comment]
yes

**Comment by michaelpnelson** [comment]
Thanks @qqnluaq ! I'll close this issue.
