### ISSUE TITLE
MVT support?

### ISSUE THREAD

**Issue by smnorris** [bcgov/smk#52]
Just throwing this out there... any plans for vector tile support (.pbf)?  https://leaflet.github.io/Leaflet.VectorGrid/vectorgrid-api-docs.html

**Comment by NicoledeGreef** [comment]
Thanks for the inquiry/suggestion.  It wasn't identified as a priority when we started scoping but we are happy to consider potential use cases for this as we move forward.

https://docs.mapbox.com/vector-tiles/specification/

**Comment by smnorris** [comment]
Thanks. Use case is display of data too dense for practical display via geojson/wfs.
For example, provincial streams 20k layer adapted for fish passage modelling: https://hillcrestgeo.ca/pg_tileserv/fish_passage.modelled_habitat_potential.html

I'm not familiar enough with smk or Leaflet.VectorGrid to know if this is at all practical.

**Comment by michaelpnelson** [comment]
We've added a demo of using Leaflet.VectorGrid to work with vector tile layers: https://github.com/bcgov/smk/tree/master/debug/customization/vector-tile-layer. The demo includes a Protobuf layer from Esri as well as a GeoJSON layer that is sliced.
