### ISSUE TITLE
Find nearby radius in km

### ISSUE THREAD

**Issue by qqnluaq** [bcgov/smk#58]
Add km as a possible unit for find nearby

**Comment by NicoledeGreef** [comment]
i could set a default kilometers value in he SMK Editor but the "kilometres" didn't show up in the site:

![image](https://user-images.githubusercontent.com/26335003/93830938-6e6fd100-fc26-11ea-8d3c-fb465c3ada35.png)

![image](https://user-images.githubusercontent.com/26335003/93830958-7a5b9300-fc26-11ea-9731-8d751033ff5d.png)

![image](https://user-images.githubusercontent.com/26335003/93831018-9e1ed900-fc26-11ea-8178-69c89a78481d.png)

**Comment by qqnluaq** [comment]
Did you update the version of smk in your project? In your project, run:
    
     npm list smk

Your should see `smk@1.0.0-beta.3`

If not, do `npm install smk@1.0.0-beta.3`

It would probably be helpful if the smk tool could help with this.
