### ISSUE TITLE
popupTemplate content not wrapping

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk#61]
beta7, Chrome on Windows 10

https://francophone-qa.apps.gov.bc.ca/bcFrancophonieMap/

popupTemplate was configured for Tourism Sites layer.  The attribute values are contained within a table structure.  Is there a CSS file that controls the font size, etc. in the popup panel?

**Comment by NicoledeGreef** [comment]
![image](https://user-images.githubusercontent.com/26335003/93830640-9c084a80-fc25-11ea-85c0-44491c50ea4f.png)

**Comment by qqnluaq** [comment]
I fixed it by adding a style tag with `overflow-wrap:anywhere` to one of the table cells, the one with the URL:
![image](https://user-images.githubusercontent.com/20274603/93835253-7d10b500-fc33-11ea-9f31-676715eb13f2.png)

![image](https://user-images.githubusercontent.com/20274603/93835266-88fc7700-fc33-11ea-953c-31ccc705db6c.png)

You will have to modify the template for this layer.

**Comment by NicoledeGreef** [comment]
thank you!
