### ISSUE TITLE
hyperlinking email and website URLs in popupTemplate content

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk#62]
beta 8

I want to configure hyperlinks on the email and website URLs.

I tried this syntax but the token within the href didn't resolve correctly:

![image](https://user-images.githubusercontent.com/26335003/93928398-1b058d80-fccf-11ea-99f4-94bae365fedc.png)

![image](https://user-images.githubusercontent.com/26335003/93928454-32dd1180-fccf-11ea-8921-aa4d1e67ed74.png)

![image](https://user-images.githubusercontent.com/26335003/93928476-3f616a00-fccf-11ea-970e-0c2627ce779a.png)

Do I need to escape the template somehow?

**Comment by qqnluaq** [comment]
This should do the trick:
`<a v-bind:href="'mailto:' + feature.properties.CONTACT_EMAIL">{{ feature.properties.CONTACT_EMAIL }}</a>`
In Vue, element attributes (`href`) are bound to template values differently than text content.
