### ISSUE TITLE
query alias in url parameters doesn't generate corrent configuration

### ISSUE THREAD

**Issue by qqnluaq** [bcgov/smk#70]

**Comment by qqnluaq** [comment]
@NicoledeGreef noted that this URL doesn't work as expected:
`https://francophone-qa.apps.gov.bc.ca/bcFrancophonieMap/?smk-query=schools-k-12,and,EARLY_FRENCH_IMMERSION_OFFERED=%22Yes%22`

I fixed it this way:
`https://francophone-qa.apps.gov.bc.ca/bcFrancophonieMap/?query=schools-k-12,and,EARLY_FRENCH_IMMERSION_OFFERED=%22YES%22&config=%7B%22tools%22:[%7B%22type%22:%22query%22,%22instance%22:%22schools-k-12--query-schools-k-12-and-early-french-immersion-offered-yes%22,%22enabled%22:true,%22position%22:%22toolbar%22%7D]%7D`

The query tool needed to be enabled, and positioned on the toolbar.

**Comment by qqnluaq** [comment]
this will work now:
`https://francophone-qa.apps.gov.bc.ca/bcFrancophonieMap/?smk-query=schools-k-12,and,EARLY_FRENCH_IMMERSION_OFFERED=%22YES%22`

I snuck in some new features:
`https://francophone-qa.apps.gov.bc.ca/bcFrancophonieMap/?smk-query=schools-k-12`
(query for all features on that layer)

and

`https://francophone-qa.apps.gov.bc.ca/bcFrancophonieMap/?smk-query=schools-k-12,and,EARLY_FRENCH_IMMERSION_OFFERED=?`
(query asks for input)

and

`https://francophone-qa.apps.gov.bc.ca/bcFrancophonieMap/?smk-query=schools-k-12,and,EARLY_FRENCH_IMMERSION_OFFERED=@`
(query finds unique values for attribute, and asks for choice)

**Comment by NicoledeGreef** [comment]
closing this ticket but have created #86
