### ISSUE TITLE
end user alters radius search value and generates a problem

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk#72]
can be seen in this draft site: 
https://francophone-qa.apps.gov.bc.ca/bcFrancophonieMap/

under the menu, choose "Find Nearby Services" and adjust the default of 3 kms to 0.3 km (in the text box)

This field should be uneditable or respond to any value entered.

"Maximum distance" is also a bit misleading given that one can drag the circle to a much larger radius than the default value

**Comment by NicoledeGreef** [comment]
![image](https://user-images.githubusercontent.com/26335003/95904272-1f601c00-0d4c-11eb-8b3d-3ee0f5d110c6.png)

**Comment by qqnluaq** [comment]
smk 1.0.0-beta.6

https://bcgov.github.io/smk/debug/feature/Tool-Identify-Config/#radius-km
