### ISSUE TITLE
point markup tool missing marker

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk#76]
smk 1.0.0-beta.5

When the markup tool is configured in a site, the point markers on the map are missing

![image](https://user-images.githubusercontent.com/26335003/96653111-2d361400-12ed-11eb-8850-4b94165a55f3.png)

**Comment by qqnluaq** [comment]
The coordinate tool shows the lat,long of the cursor position. The screenshot shows the point marker mode of the markup tool. Do you mean the markup tool?

I have tested the markup tool, and don't see any problems.
What  app are you seeing this in?

**Comment by NicoledeGreef** [comment]
Yes, the point markup tool is the issue, not the coordinate tool.  Apology for incorrect terminology.

**Steps to recreate:**
1 - Create a new site using the latest (CLI v1.0.0-beta.11)
2 - use the View button in the CLI and review the lack of markers when clicking on the map using the markup point tool as in screenshot above

**Comment by NicoledeGreef** [comment]
created a net new site and confirmed the missing markers; see parameters used in creation of the site:
![image](https://user-images.githubusercontent.com/26335003/97219746-a6b78180-1787-11eb-9660-dd88e6a86529.png)

**Comment by NicoledeGreef** [comment]
still seems to be an issue in beta8:
![image](https://user-images.githubusercontent.com/26335003/97346760-180b3900-1849-11eb-90bb-c3264590e63a.png)

do i need to update the smk-cli as well?

**Comment by qqnluaq** [comment]
I'll have to update the smk-cli first, so that smk-cli is depending on beta.8.

This is happening because of the issue mentioned in https://github.com/bcgov/smk-cli/issues/49..

**Comment by NicoledeGreef** [comment]
ah gotcha fine.  when i deploy the site and review it outside of the SMK Editor, i do indeed see the markers.
