### ISSUE TITLE
"vector" data doco enhancement

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk#81]
beta5/v1.0

Can we note somewhere that "vector" data sourced from Geoserver will be limited to 500 features if referencing via WFS?  When attempting to reference BCGov Geoserver based data  with >500 features, the WMS to application/json workaround can be used. We encountered this will schools data in the francophone app.

**Comment by qqnluaq** [comment]
This might be better in the FAQ or wiki. The 500 feature limit is also configurable in Geoserver, so its specific to the instance (though I think 500 is the default).

**Comment by NicoledeGreef** [comment]
OK thanks - we will handle this one in an FAQ.

**Comment by NicoledeGreef** [comment]
https://github.com/bcgov/smk-cli/wiki/Simple-Map-Kit-and-SMK-Editor-FAQs

see: "I want to user Geoserver..."
