### ISSUE TITLE
"identify" tool properties not documented

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk#83]
beta5

example config from a site:

        {
            "order": 5,
            "position": "list-menu",
            "icon": "perm_device_info",
            "title": "Find Nearby Services",
            "command": {
                "select": false,
                "radius": false,
                "radiusUnit": false,
                "nearBy": true,
                _"attributeMode": false_
            },
            "radius": "1",
            "radiusUnit": "km",
            "type": "identify",
            "enabled": true,
            "showPanel": true,
            "showWidget": true,
            _style": {
                "strokeWidth": 1,
                "strokeStyle": "1, 1",
                "strokeColor": "#000000",
                "strokeOpacity": 0.8,
                "fillColor": "#000000",
                "fillOpacity": 0.5,
                "markerSize": [
                    20,
                    20
                ],
                "markerOffset": [
                    10,
                    0
                ]
            },_
            "showTitle": true
        },

Doc link: https://bcgov.github.io/smk/docs/configuration/tools/identify

-->no reference to "style" property and sub-properties found.
-->should "attributeView" in the docs be "attributeMode"?

**Comment by qqnluaq** [comment]
I will change the `attributeView` property to `attributeMode` to be consistent with the command sub-property, and because the name is clearer for its purpose. For backward compatibility, the `attributeView` property will still be read, but the documentation and smk editor will use `attributeMode`.
