### ISSUE TITLE
query URL parameters should run query instead of  prompting for "Search"

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk#86]
When a complete & valid query is supplied via URL the query should be run right off the bat, not prompt the user to click Search.  This is how IMF2 and DMF handled similar requests.

e.g. see difference between SMK implementation and IMF2 implementation:
https://francophone-qa.apps.gov.bc.ca/bcFrancophonieMap/?query=schools-k-12,and,EARLY_FRENCH_IMMERSION_OFFERED=%22YES%22

https://maps.gov.bc.ca/ess/hm/imap4m/?catalogLayers=7970&attributeSearch=7970,EARLY_FRENCH_IMMERSION_OFFERED,YES

When a request is made, auto-run the search and display the results in the list, as such:

![image](https://user-images.githubusercontent.com/26335003/97340861-8b10b180-1841-11eb-94a4-8c4ef797c1eb.png)

Not intermediate step as currently required (illustrated below):
![image](https://user-images.githubusercontent.com/26335003/97341001-ba272300-1841-11eb-93ae-79ad8b24d4eb.png)

**Comment by NicoledeGreef** [comment]
@qqnluaq - can you please estimate hours for this one?

**Comment by qqnluaq** [comment]
I estimate 4 hrs

**Comment by NicoledeGreef** [comment]
thanks - i'd like to proceed with this one ASAP.

**Comment by NicoledeGreef** [comment]
Verified:
https://smk-fap-fcb-rt-b16795-dev.apps.silver.devops.gov.bc.ca/?query=schools-k-12,and,EARLY_FRENCH_IMMERSION_OFFERED=%22YES%22
