### ISSUE TITLE
migrate smk package in npm to the bcgov group

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/smk#94]
smk was initially set up outside the bcgov organization in npm.  nicole and ben have been granted membership to the bcgov group so that the package can be published within the bcgov org, mimicking github.

**Comment by NicoledeGreef** [comment]
Thanks for migrating to the @bcgov.  Do we need to ensure all docs reflect these changes?

Example install instructions:

npm i smk
should now be:
npm i @bcgov/smk
?

**Comment by qqnluaq** [comment]
docs have been updated

**Comment by NicoledeGreef** [comment]
right - thanks.  i was thinking of the wiki page: https://github.com/bcgov/smk-cli/wiki/Quick-Start-Installation-Guide but i am going to remove that page since our launch promo material didn't point to that page.
