### ISSUE TITLE
Identify tool not finding underlying features

### ISSUE THREAD

**Issue by LewGreentree** [bcgov/smk#96]
I have loaded a geojson dataset into smk.  When I query polygons in the dataset, smk goes into an endless "fetching features" loop.  The dataset appears correct in QGIS, I can query the polygons and see their attributes there.  Also, tested it with the QGIS2WEB plugin and the 'web app" created can be queried without any issues.

**This appears to be a bug in smk.** 

## How to reproduce

- SMK version I'm using: 1.0.2
- Browser (with version) I'm using: Chrome Version 87.0.4280.141 (Official Build) (32-bit)
- OS/Platform (with version) I'm using: Windows 10 Enterprise

## Minimal example reproducing the issue: 
[vi_fc_silv_svw_FD.zip](https://github.com/bcgov/smk/files/5805438/vi_fc_silv_svw_FD.zip)

-I've attached a zipped geojson to this request.

**Comment by NicoledeGreef** [comment]
Verified locally using smk v1.0.2; it is an issue when deployed to GitHub pages as well.

![image](https://user-images.githubusercontent.com/26335003/104767687-6e3d9900-5721-11eb-8106-5d8ce3e4bc20.png)

**Comment by NicoledeGreef** [comment]
tested the file contents via https://geojson.io/ and was able to identify on features.

**Comment by qqnluaq** [comment]
The data has a problem, most of the features have a geometry object with no coordinates. This is invalid geojson, hence the error.
![image](https://user-images.githubusercontent.com/20274603/105063897-22486800-5a31-11eb-89ca-afadfc5a8c6f.png)

**Comment by LewGreentree** [comment]
Benjamin. thank you for troubleshooting this issue. I discovered that the metadata record for my input layer has an attribute called  Geometry_Exist_Ind which I will include in my ogr2ogr sql statement that extracts the data from the BCGW.

![image](https://user-images.githubusercontent.com/21177084/105068638-06939080-5a36-11eb-81a8-3d744234953a.png)
